[package]
name = "rspack_sources"
version = "0.1.16"
edition = "2021"
authors = ["h-a-n-a <andywangsy@gmail.com>", "ahabhgk <ahabhgk@gmail.com>"]
resolver = "2"
license = "MIT"
description = "Rusty webpack-sources port."
keywords = ["sources", "sourcemap"]
repository = "https://github.com/speedy-js/rspack-sources"
documentation = "https://docs.rs/rspack-sources"
readme = "README.md"

include = ["/src/**/*.rs", "/*.toml", "/LICENSE", "/README.md"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dyn-clone = "1"
hashbrown = "0.12"
once_cell = "1"
parking_lot = "0.12"
dashmap = "5"
substring = "1"
smallvec = "1.10.0"
memchr = "2.5.0"

[dev-dependencies]
twox-hash = "1"
base64-simd = "0.7"
