[package]
name = "rspack-sources"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
parking_lot = "0.12"
smol_str = "0.1"

[dev-dependencies]
twox-hash = "1"
base64-simd = "0.7"
