[package]
name = "rspack_sources"
version = "0.2.10"
edition = "2021"
authors = ["h-a-n-a <andywangsy@gmail.com>", "ahabhgk <ahabhgk@gmail.com>"]
resolver = "2"
license = "MIT"
description = "Rusty webpack-sources port."
keywords = ["sources", "sourcemap"]
repository = "https://github.com/web-infra-dev/rspack-sources"
documentation = "https://docs.rs/rspack-sources"
readme = "README.md"

include = ["/src/**/*.rs", "/*.toml", "/LICENSE", "/README.md"]

[lints.rust]
unsafe_code  = "warn"
missing_docs = "warn"

[lints.clippy]
dbg_macro     = "warn"
todo          = "warn"
unimplemented = "warn"
print_stdout  = "warn"
print_stderr  = "warn"

[[bench]]
name    = "bench"
path = "benches/bench.rs"
harness = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dyn-clone = "1"
rustc-hash = "1"
dashmap = "5"
substring = "1"
smallvec = "1.11.2"
memchr = "2.6.4"
str_indices = "0.4.3"

codspeed-criterion-compat = { version = "2.3.3", default-features = false, optional = true }

[dev-dependencies]
twox-hash = "1"
base64-simd = "0.7"
regex = "1.10.2"
criterion = { version = "0.5.1", default-features = false }

[features]
codspeed = ["codspeed-criterion-compat"]
