name: Lint

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt,clippy,rust-docs

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Cargo docs
        run: RUSTDOCFLAGS='-D warnings' cargo doc

      - name: Clippy
        run: cargo clippy -- -D warnings
